Repository SumitGorai01/TechieBlog, pull requests merged in 2025-01, with the labels that each got.

#3 Added search functionality
  src/appwrite/config.js
  src/components/Header/Header.jsx
  src/components/Header/Searchbar.jsx
  src/main.jsx
  src/pages/SearchedBlogs.jsx
Labels: enhancement, SWOC, BEGINNER

#11 updating scroll button to the home page
  index.html
  src/index.css
  src/store/store.js
Labels: SWOC, BEGINNER

#14 Added error boundary and lazy suspense
  package-lock.json
  package.json
  src/App.jsx
  src/components/errors/Error404.jsx
  src/components/errors/SomethingWentWrong.jsx
  src/components/loaders/Loading.jsx
  src/components/post-form/PostForm.jsx
  src/main.jsx
  src/pages/AllPosts.jsx
  src/pages/Post.jsx
  vercel.json
Labels: enhancement, SWOC, INTERMEDIATE

#30 Fixed: Post Deletion
  src/pages/Post.jsx
Labels: enhancement, SWOC, BEGINNER, INTERMEDIATE, SWOC 5.0

#36 Added Dynamic Copywrite year
  src/components/Footer/Footer.jsx
Labels: enhancement, SWOC, BEGINNER, SWOC 5.0

#37 Updated Twitter Icon to X and Added Brand Colors on Hover in Footer
  package-lock.json
  package.json
  src/components/Footer/Footer.jsx
  src/main.jsx
Labels: enhancement, SWOC, BEGINNER, SWOC 5.0

#41 Improve UI for All Posts Page Using Tailwind CSS
  src/appwrite/config.js
  src/components/PostCard.jsx
  src/components/post-form/PostForm.jsx
  src/pages/AllPosts.jsx
  src/pages/Post.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#49 Fix footer style
  src/App.jsx
  src/components/Footer/Footer.jsx
Labels: enhancement, SWOC, INTERMEDIATE, SWOC 5.0

#53 Feature: Added Hamburger Menu
  package-lock.json
  package.json
  src/components/Header/Header.jsx
  src/components/Header/Searchbar.jsx
  src/pages/Home.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#54 Added forgot password option
  src/App.jsx
  src/appwrite/auth.js
  src/components/ForgotPassword.jsx
  src/components/Login.jsx
  src/components/ResetPassword.jsx
  src/components/index.js
  src/main.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#62 Added testimonial section
  package-lock.json
  package.json
  src/components/Testimonials.jsx
  src/components/index.js
  src/pages/Home.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#65 Feature: Contributors page
  package-lock.json
  package.json
  src/components/Footer/Footer.jsx
  src/components/contributors/contribution.js
  src/components/contributors/contributorsLink.jsx
  src/main.jsx
  src/pages/Contributors.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#66 updating the social icons and added a black border
  src/components/Footer/Footer.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#72 Bug/search
  src/components/Footer/Footer.jsx
  src/components/contributors/contributorsLink.jsx
  src/pages/Home.jsx
  src/pages/SearchedBlogs.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#73 fixed: footer contribution link
  src/components/Footer/Footer.jsx
  src/components/contributors/contributorsLink.jsx
  src/pages/Home.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#77 Update navbar to solve #71
  src/components/Header/Header.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#78 Fixed Alignment of Email and Password Fields in Form Layout
  src/components/Input.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#75 Feature: Adding Dark Mode
  package-lock.json
  package.json
  src/App.jsx
  src/components/Footer/Footer.jsx
  src/components/Header/Header.jsx
  src/components/Header/LogoutBtn.jsx
  src/components/Header/Searchbar.jsx
  src/components/PostCard.jsx
  src/components/RTE.jsx
  src/components/post-form/PostForm.jsx
  src/pages/AddPost.jsx
  src/pages/AllPosts.jsx
  src/pages/Contributors.jsx
  src/pages/EditPost.jsx
  src/pages/Home.jsx
  src/pages/Post.jsx
  src/pages/SearchedBlogs.jsx
  src/store/store.js
  src/store/themeSlice.js
  tailwind.config.js
Labels: SWOC, ADVANCE, SWOC 5.0

#83 Latest Post Page has uneven alignment and images are not of equal size #44
  src/components/PostCard.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#85 Cursor Trail effect added
  index.html
Labels: SWOC, ADVANCE, SWOC 5.0

#89 Added illustration
  src/assets/tech-blog-illustration.png
  src/pages/Home.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#91 Twitter icon is outdated #86
  src/components/Footer/Footer.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#93 updating the alignment of all screen size
  src/components/Input.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#96 updating the fix alignment of the footer
  src/components/Footer/Footer.jsx
Labels: SWOC, BEGINNER, SWOC 5.0

#97 Feature: Added settings and change password
  src/appwrite/auth.js
  src/components/ForgotPassword.jsx
  src/components/Header/Header.jsx
  src/components/Header/LogoutBtn.jsx
  src/components/Header/Menu.jsx
  src/main.jsx
  src/pages/ChangePassword.jsx
  src/pages/Settings.jsx
  tailwind.config.js
Labels: SWOC, ADVANCE, SWOC 5.0

#100 Feature: Added profile page
  src/appwrite/config.js
  src/components/Header/Menu.jsx
  src/main.jsx
  src/pages/Profile.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#101 [BUG] Made responsive for mobile view
  src/components/PostCard.jsx
  src/components/container/Container.jsx
  src/pages/AllPosts.jsx
  src/pages/Home.jsx
  src/pages/Profile.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#108 Add Relative Time Display for Blog Posts
  package-lock.json
  package.json
  src/components/PostCard.jsx
  src/pages/AllPosts.jsx
  src/utils/TimeAgo.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#109 Chatbot added
  index.html
Labels: SWOC, ADVANCE, SWOC 5.0

#111 Added the New Logo
  src/assets/logo.png
  src/assets/logoold.png
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#114 enhanced login and signup
  src/components/Button.jsx
  src/components/Login.jsx
  src/components/Signup.jsx
  src/index.css
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#116 In the Nav Bar , There is two home buttons #45
  src/components/Header/Header.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#121 [Feature]: Bottom navigation bar
  src/App.jsx
  src/components/Header/Header.jsx
  src/components/Header/Menu.jsx
  src/components/Header/MobileNavbar.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#122 uneven images in Home page #119
  src/components/PostCard.jsx
Labels: SWOC, BEGINNER, SWOC 5.0

#123 Fixed Scroll-to-Top Button Overlap with Chatbox
  src/components/Footer/Footer.jsx
Labels: SWOC, BEGINNER, SWOC 5.0

#125 enhanced testimonial page
  package-lock.json
  package.json
  src/components/Testimonials.jsx
  src/index.css
Labels: SWOC, ADVANCE, SWOC 5.0

#128 updating the ui/ux of signup page
  src/components/Signup.jsx
Labels: SWOC, BEGINNER, SWOC 5.0

#126 feat/ Added dark mode
  src/App.jsx
  src/components/Footer/Footer.jsx
  src/components/ForgotPassword.jsx
  src/components/Header/Header.jsx
  src/components/Header/Menu.jsx
  src/components/Header/MobileNavbar.jsx
  src/components/Header/Searchbar.jsx
  src/components/Login.jsx
  src/components/PostCard.jsx
  src/components/RTE.jsx
  src/components/Signup.jsx
  src/components/Testimonials.jsx
  src/components/errors/Error404.jsx
  src/components/errors/SomethingWentWrong.jsx
  src/components/post-form/PostForm.jsx
  src/pages/AddPost.jsx
  src/pages/AllPosts.jsx
  src/pages/Contributors.jsx
  src/pages/EditPost.jsx
  src/pages/Home.jsx
  src/pages/Post.jsx
  src/pages/SearchedBlogs.jsx
  src/store/store.js
  src/store/themeSlice.js
  tailwind.config.js
Labels: SWOC, ADVANCE, SWOC 5.0

#133 Resolved and Update Error404.jsx
  src/components/errors/Error404.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#134 Solved: Theme toggle in smaller devices
  src/components/Header/Header.jsx
  src/components/Header/Menu.jsx
  src/components/errors/Error404.jsx
  src/store/themeSlice.js
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#136 Enhance/profile
  src/components/Header/Menu.jsx
  src/pages/Profile.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#147 made faq page
  src/components/FAQ.jsx
  src/components/Header/Header.jsx
  src/index.css
  src/main.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#148 enhance loading and settings components with dark mode support
  src/components/loaders/Loading.jsx
  src/pages/Settings.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#150 Enhance: Added icons to navlinks
  src/components/Header/Header.jsx
  src/components/Header/LogoutBtn.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#153 Fixed: Extra theme toggler in larger devices
  src/components/Header/Header.jsx
Labels: SWOC, BEGINNER, SWOC 5.0

#154 Update the styling in Dark Mode
  src/components/FAQ.jsx
  src/pages/ChangePassword.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#156 Added terms and conditions page
  src/components/Signup.jsx
  src/components/Terms.jsx
  src/index.css
  src/main.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#164 Enhanced testimonials page
  src/components/Testimonials.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#167 Enhance: Added email and joined date in Profile
  src/pages/Profile.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#173 [BUG] Changes dark mode color for testimonials
  src/components/Testimonials.jsx
  src/index.css
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#175 Implemented redux-persist
  package-lock.json
  package.json
  src/main.jsx
  src/store/store.js
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#176 Updated post page
  src/appwrite/auth.js
  src/pages/Post.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#179 Issue #171 resolved: FAQ page UI
  package-lock.json
  package.json
  src/components/FAQ.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#180 Enhance footer with updated mission statement, dark mode text color and dynamic hover effects
  src/components/Footer/Footer.jsx
  src/pages/Home.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#181 added about us page
  src/components/AboutUs.jsx
  src/components/Header/Header.jsx
  src/index.css
  src/main.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#165 changes made
  src/components/Footer/Footer.jsx
  src/components/Testimonials.jsx
  src/index.css
  src/pages/Home.jsx
  src/store/themeSlice.js
Labels: SWOC, BEGINNER, SWOC 5.0

#182 Implemented a React component for rendering Markdown content.
  package-lock.json
  package.json
  src/components/MarkdownDisplay.jsx
  src/pages/Post.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#184 added contact us page
  src/components/ContactUs.jsx
  src/components/Header/Header.jsx
  src/main.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#186 Enhanced: About Us and Contact Us
  src/components/AboutUs.jsx
  src/components/ContactUs.jsx
  src/index.css
Labels: SWOC, BEGINNER, SWOC 5.0

#190 Enhanced feedback page
  src/components/FeedbackPage.jsx
Labels: SWOC, BEGINNER, SWOC 5.0

#191 Added events page
  src/components/Events.jsx
  src/components/Header/Header.jsx
  src/main.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#211 Email Authentication
  .env.sample
  src/appwrite/auth.js
  src/components/Login.jsx
  src/components/Signup.jsx
  src/main.jsx
  src/pages/Verify.jsx
Labels: SWOC, ADVANCE, SWOC 5.0
