Repository SumitGorai01/TechieBlog, pull requests merged in 2025-08, with the labels that each got.

#546 Dummy pull request on behalf of #519 (Advance)
  .env.example
  package-lock.json
  package.json
Labels: Advanced, SSoC25

#566 Articles Page added
  src/main.jsx
  src/pages/Articles.jsx
  src/pages/Home.jsx
Labels: Advanced, SSoC25

#611 Bug Fix
  src/components/Events.jsx
Labels: Beginner, SSoC25

#621 Profile Page UI Updated
  package-lock.json
  src/appwrite/auth.js
  src/pages/Profile.jsx
Labels: Intermediate, SSoC25
