Repository SumitGorai01/TechieBlog, pull requests merged in 2025-02, with the labels that each got.

#217 added events/webinar page
  new_backend/package-lock.json
  new_backend/package.json
  new_backend/server.js
  package-lock.json
  package.json
  src/components/AddEvent.jsx
  src/components/Events.jsx
  src/main.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#219 Functionality for Liking Blogs
  src/appwrite/config.js
  src/pages/Post.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#223 Event page responsive for mobile device
  src/components/Events.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#225 🚀 Enhanced User Experience with Hover Effects in Feedback Form 🎨
  src/components/FeedbackPage.jsx
Labels: SWOC, BEGINNER, SWOC 5.0

#229 feat: improved add event frontend
  package-lock.json
  package.json
  src/components/AddEvent.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#233 Comment backend
  .env.sample
  src/appwrite/comment.js
  src/components/AddComment.jsx
  src/conf/conf.js
  src/main.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#242 Appwrite configuration Guide
  1.png
  2.png
  3.png
  4.png
  README.md
Labels: SWOC, ADVANCE, SWOC 5.0

#247 Comment Frontend
  package-lock.json
  src/index.css
  src/pages/Post.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#256 enhanced contributors page
  src/pages/Contributors.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#257 made register for workshop page responsive
  src/components/Register.jsx
Labels: SWOC, BEGINNER, SWOC 5.0

#267 About Us Page
  package-lock.json
  package.json
  src/components/AboutUs.jsx
Labels: SWOC, ADVANCE, SWOC 5.0

#279 contact us form ui improve
  src/components/ContactUs.jsx
Labels: SWOC, BEGINNER, SWOC 5.0

#281 twitter logo update
  src/components/AboutUs.jsx
Labels: SWOC, BEGINNER, SWOC 5.0

#278 FAQ Page
  src/components/FAQ.jsx
  tailwind.config.js
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#290 Scroll to top button enhancement
  package-lock.json
  package.json
  src/components/Footer/Footer.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#286 Update FAQ.jsx
  src/components/FAQ.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#299 enhanced ui of feedback page
  src/components/FeedbackPage.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#305 updated Header.jsx and tailwind.config.js
  src/components/Header/Header.jsx
  tailwind.config.js
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#306 Update Events.jsx
  src/components/Events.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#310 Update FeedbackPage.jsx
  src/components/FeedbackPage.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#313 enhanced UI of terms and conditions
  src/components/Terms.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#314 enhanced UI of register for workshop page
  src/components/Register.jsx
Labels: SWOC, INTERMEDIATE, SWOC 5.0

#318 Added a scroll bar
  src/index.css
Labels: SWOC, INTERMEDIATE, SWOC 5.0
